
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
