FROM python:3.9-slim

WORKDIR /app

# remove cache
# RUN apt-get update && apt-get install -y gcc && apt-get clean


RUN pip install --upgrade pip

# Copy and install requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Command to run Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "project.wsgi:application"]
